// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: message.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from message.proto</summary>
public static partial class MessageReflection {

  #region Descriptor
  /// <summary>File descriptor for message.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MessageReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg1tZXNzYWdlLnByb3RvImkKB01lc3NhZ2USDQoFbWVyZ2UYASABKAMSDAoE",
          "Ym9keRgCIAEoDBIRCgloZWFydGJlYXQYAyABKAgSDAoEY29kZRgEIAEoAxIP",
          "CgdtZXNzYWdlGAUgASgJEg8KB2hlYWRlcnMYBiABKAliBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Message), global::Message.Parser, new[]{ "Merge", "Body", "Heartbeat", "Code", "Message_", "Headers" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Message : pb::IMessage<Message>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Message> _parser = new pb::MessageParser<Message>(() => new Message());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Message> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MessageReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Message() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Message(Message other) : this() {
    merge_ = other.merge_;
    body_ = other.body_;
    heartbeat_ = other.heartbeat_;
    code_ = other.code_;
    message_ = other.message_;
    headers_ = other.headers_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Message Clone() {
    return new Message(this);
  }

  /// <summary>Field number for the "merge" field.</summary>
  public const int MergeFieldNumber = 1;
  private long merge_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Merge {
    get { return merge_; }
    set {
      merge_ = value;
    }
  }

  /// <summary>Field number for the "body" field.</summary>
  public const int BodyFieldNumber = 2;
  private pb::ByteString body_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString Body {
    get { return body_; }
    set {
      body_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "heartbeat" field.</summary>
  public const int HeartbeatFieldNumber = 3;
  private bool heartbeat_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Heartbeat {
    get { return heartbeat_; }
    set {
      heartbeat_ = value;
    }
  }

  /// <summary>Field number for the "code" field.</summary>
  public const int CodeFieldNumber = 4;
  private long code_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Code {
    get { return code_; }
    set {
      code_ = value;
    }
  }

  /// <summary>Field number for the "message" field.</summary>
  public const int Message_FieldNumber = 5;
  private string message_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Message_ {
    get { return message_; }
    set {
      message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "headers" field.</summary>
  public const int HeadersFieldNumber = 6;
  private string headers_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Headers {
    get { return headers_; }
    set {
      headers_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Message);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Message other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Merge != other.Merge) return false;
    if (Body != other.Body) return false;
    if (Heartbeat != other.Heartbeat) return false;
    if (Code != other.Code) return false;
    if (Message_ != other.Message_) return false;
    if (Headers != other.Headers) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Merge != 0L) hash ^= Merge.GetHashCode();
    if (Body.Length != 0) hash ^= Body.GetHashCode();
    if (Heartbeat != false) hash ^= Heartbeat.GetHashCode();
    if (Code != 0L) hash ^= Code.GetHashCode();
    if (Message_.Length != 0) hash ^= Message_.GetHashCode();
    if (Headers.Length != 0) hash ^= Headers.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Merge != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Merge);
    }
    if (Body.Length != 0) {
      output.WriteRawTag(18);
      output.WriteBytes(Body);
    }
    if (Heartbeat != false) {
      output.WriteRawTag(24);
      output.WriteBool(Heartbeat);
    }
    if (Code != 0L) {
      output.WriteRawTag(32);
      output.WriteInt64(Code);
    }
    if (Message_.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Message_);
    }
    if (Headers.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Headers);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Merge != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Merge);
    }
    if (Body.Length != 0) {
      output.WriteRawTag(18);
      output.WriteBytes(Body);
    }
    if (Heartbeat != false) {
      output.WriteRawTag(24);
      output.WriteBool(Heartbeat);
    }
    if (Code != 0L) {
      output.WriteRawTag(32);
      output.WriteInt64(Code);
    }
    if (Message_.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Message_);
    }
    if (Headers.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Headers);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Merge != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Merge);
    }
    if (Body.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Body);
    }
    if (Heartbeat != false) {
      size += 1 + 1;
    }
    if (Code != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Code);
    }
    if (Message_.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Message_);
    }
    if (Headers.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Headers);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Message other) {
    if (other == null) {
      return;
    }
    if (other.Merge != 0L) {
      Merge = other.Merge;
    }
    if (other.Body.Length != 0) {
      Body = other.Body;
    }
    if (other.Heartbeat != false) {
      Heartbeat = other.Heartbeat;
    }
    if (other.Code != 0L) {
      Code = other.Code;
    }
    if (other.Message_.Length != 0) {
      Message_ = other.Message_;
    }
    if (other.Headers.Length != 0) {
      Headers = other.Headers;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Merge = input.ReadInt64();
          break;
        }
        case 18: {
          Body = input.ReadBytes();
          break;
        }
        case 24: {
          Heartbeat = input.ReadBool();
          break;
        }
        case 32: {
          Code = input.ReadInt64();
          break;
        }
        case 42: {
          Message_ = input.ReadString();
          break;
        }
        case 50: {
          Headers = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Merge = input.ReadInt64();
          break;
        }
        case 18: {
          Body = input.ReadBytes();
          break;
        }
        case 24: {
          Heartbeat = input.ReadBool();
          break;
        }
        case 32: {
          Code = input.ReadInt64();
          break;
        }
        case 42: {
          Message_ = input.ReadString();
          break;
        }
        case 50: {
          Headers = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
